# Generated by Django 3.1.3 on 2020-11-20 13:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codeapp', '0002_python_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='python',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
